# Generated by Django 4.2 on 2023-05-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porfolio', '0002_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer_Ditails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_item', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Project_Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('past_price', models.CharField(max_length=20)),
                ('present_price', models.CharField(max_length=20)),
            ],
        ),
    ]
