# Generated by Django 4.2 on 2023-05-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porfolio', '0003_offer_ditails_project_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio_Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/')),
                ('hovereffect_title', models.CharField(max_length=20)),
                ('hovereffect_para', models.CharField(max_length=20)),
            ],
        ),
    ]
