# Generated by Django 4.2.1 on 2023-05-08 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('porfolio', '0005_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featureplans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('packageList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='porfolio.project_plans')),
            ],
        ),
    ]
