# Generated by Django 4.2.1 on 2023-05-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porfolio', '0008_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('website', models.CharField(max_length=100)),
            ],
        ),
    ]
